# Generated by Django 5.1.7 on 2025-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('False', 'کار جو'), ('True', 'کار فرما')], default='False', max_length=50, verbose_name='جنسیت'),
        ),
    ]
