# Generated by Django 5.1.7 on 2025-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_acitve',
            field=models.BooleanField(default=False, verbose_name='فعال بودن'),
        ),
    ]
