# Generated by Django 5.1.7 on 2025-03-21 17:12

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('time', models.IntegerField(verbose_name='چند روز')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نوع')),
                ('price', models.ImageField(upload_to='', verbose_name='هزینه')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUplode.uplode_to, verbose_name='تصویر ')),
                ('discription', models.TextField(verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.priceadvertisement', verbose_name='مدت زمان')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.typeadvertisement', verbose_name='نوع')),
            ],
        ),
    ]
