# Generated by Django 5.1.7 on 2025-04-18 08:14

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='time',
        ),
        migrations.RemoveField(
            model_name='priceadvertisement',
            name='time',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت تبلیغ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درج'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='state',
            field=models.TextField(default='برنامه نویسی', verbose_name='مهارت'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='time_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUplode.uplode_to, verbose_name='تصویر '),
        ),
        migrations.AlterField(
            model_name='priceadvertisement',
            name='price',
            field=models.IntegerField(verbose_name=' قیمت به ازای هر روز'),
        ),
        migrations.AlterField(
            model_name='typeadvertisement',
            name='price',
            field=models.IntegerField(verbose_name='هزینه'),
        ),
    ]
