# Generated by Django 5.1.7 on 2025-04-18 08:40

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_remove_advertisement_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUplode.uplode_to, verbose_name='تصویر '),
        ),
    ]
